import type { Metadata } from "next";
import "../globals.css";
import "leaflet/dist/leaflet.css";
import { ReduxProvider } from "../redux/ReduxProvider";
import TopMenu from "@/Components/Navigation/TopMenu";
import { ReactNode } from "react";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { TranslationButton } from "@/Components/Shared/TranslationButton";
import BotonesFlotantes from "@/Components/ask_for_help/contenedor";
import { AuthProvider } from "../lib/hooks/usoAutentificacion"; // lo tenías en el root


// loaders de mensajes
const messagesMap = {
  en: () => import("../../../messages/en.json").then((m) => m.default),
  es: () => import("../../../messages/es.json").then((m) => m.default),
};

// generar rutas estáticas /en y /es
export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "es" }];
}

export const metadata: Metadata = {
  title: "Servineo",
  description: "Generated by create next app",
};

type LocaleType = "en" | "es"; // Define un tipo para las locales válidas

type Props = {
  children: ReactNode;
  // Next 15 pasa params como Promise en layouts async
  params: Promise<{ locale: string }>;
};

export default async function LocaleLayout({ children, params }: Props) {
  const resolvedParams = await params;
  const locale = resolvedParams.locale;

  const validLocales = ["en", "es"] as const;
  if (!validLocales.find(v => v === locale)) {
    notFound();
  }
  const secureLocale = locale as LocaleType;
  const loader = messagesMap[secureLocale]; // Usa el tipo seguro
  if (!loader) {
    notFound();
  }

  const messages = await loader();

  // 🚫 Aquí YA NO hay <html> ni <body>
  return (
    <NextIntlClientProvider locale={locale} messages={messages}>
      <ReduxProvider>
        <AuthProvider>
          <div className="text-black fixed bottom-7 right-7 z-[9999]">
            <TranslationButton />
            <BotonesFlotantes />
          </div>
          <div>
            <TopMenu />
          </div>
          {children}
        </AuthProvider>
      </ReduxProvider>
    </NextIntlClientProvider>
  );
}
